
server:
  port: 8081
spring:
  application:
    name: 'informacoes-cadastrais'
  datasource:
    password: 'admin-tcc-puc'
    username: 'admin'
    url: jdbc:mysql://authdb.cqk3oq68g2xq.us-east-1.rds.amazonaws.com:3306/informacoes-cadastrais?serverTimezone=GMT
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://ec2-3-234-229-225.compute-1.amazonaws.com:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri:  https://api-server-authenticate.herokuapp.com/user
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: <>
      secret-key: <>
    end-point:
      uri-criar: https://sqs.us-east-1.amazonaws.com/124223312961/criar_pedido_status
      uri-atualizar: https://sqs.us-east-1.amazonaws.com/124223312961/atualizar_pedido_status