spring:
  application:
    name: 'informacoes-cadastrais'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/informacoes-cadastrais
    driver-class-name: org.mariadb.jdbc.Driver
  hibernate:
    ddl-auto: update
  h2:
    console:
      enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka