spring:
  application:
    name: 'informacoes-cadastrais'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/informacoes-cadastrais
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user


cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: <>
      secret-key: <>
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/124223312961/criar_pedido_status